<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('banks')->insert([
            ['id' => 1, 'sandi_bank' => '002', 'nama_bank' => 'BANK BRI'],
            ['id' => 2, 'sandi_bank' => '422', 'nama_bank' => 'BANK BRI SYARIAH'],
            ['id' => 3, 'sandi_bank' => '003', 'nama_bank' => 'BANK EKSPOR INDONESIA'],
            ['id' => 4, 'sandi_bank' => '008', 'nama_bank' => 'BANK MANDIRI'],
            ['id' => 5, 'sandi_bank' => '009', 'nama_bank' => 'BANK BNI'],
            ['id' => 6, 'sandi_bank' => '011', 'nama_bank' => 'BANK DANAMON'],
            ['id' => 7, 'sandi_bank' => '013', 'nama_bank' => 'PERMATA BANK'],
            ['id' => 8, 'sandi_bank' => '014', 'nama_bank' => 'BANK BCA'],
            ['id' => 9, 'sandi_bank' => '016', 'nama_bank' => 'BANK BII'],
            ['id' => 10, 'sandi_bank' => '019', 'nama_bank' => 'BANK PANIN'],
            ['id' => 11, 'sandi_bank' => '020', 'nama_bank' => 'BANK ARTA NIAGA KENCANA'],
            ['id' => 12, 'sandi_bank' => '022', 'nama_bank' => 'BANK NIAGA'],
            ['id' => 13, 'sandi_bank' => '023', 'nama_bank' => 'BANK BUANA IND'],
            ['id' => 14, 'sandi_bank' => '026', 'nama_bank' => 'BANK LIPPO'],
            ['id' => 15, 'sandi_bank' => '028', 'nama_bank' => 'BANK NISP'],
            ['id' => 16, 'sandi_bank' => '030', 'nama_bank' => 'AMERICAN EXPRESS BANK LTD'],
            ['id' => 17, 'sandi_bank' => '031', 'nama_bank' => 'CITIBANK N.A.'],
            ['id' => 18, 'sandi_bank' => '032', 'nama_bank' => 'JP. MORGAN CHASE BANK, N.A.'],
            ['id' => 19, 'sandi_bank' => '033', 'nama_bank' => 'BANK OF AMERICA, N.A'],
            ['id' => 20, 'sandi_bank' => '034', 'nama_bank' => 'ING INDONESIA BANK'],
            ['id' => 21, 'sandi_bank' => '036', 'nama_bank' => 'BANK MULTICOR TBK.'],
            ['id' => 22, 'sandi_bank' => '037', 'nama_bank' => 'BANK ARTHA GRAHA'],
            ['id' => 23, 'sandi_bank' => '039', 'nama_bank' => 'BANK CREDIT AGRICOLE INDOSUEZ'],
            ['id' => 24, 'sandi_bank' => '040', 'nama_bank' => 'THE BANGKOK BANK COMP. LTD'],
            ['id' => 25, 'sandi_bank' => '041', 'nama_bank' => 'THE HONGKONG & SHANGHAI B.C.'],
            ['id' => 26, 'sandi_bank' => '042', 'nama_bank' => 'THE BANK OF TOKYO MITSUBISHI UFJ LTD'],
            ['id' => 27, 'sandi_bank' => '045', 'nama_bank' => 'BANK SUMITOMO MITSUI INDONESIA'],
            ['id' => 28, 'sandi_bank' => '046', 'nama_bank' => 'BANK DBS INDONESIA'],
            ['id' => 29, 'sandi_bank' => '047', 'nama_bank' => 'BANK RESONA PERDANIA'],
            ['id' => 30, 'sandi_bank' => '048', 'nama_bank' => 'BANK MIZUHO INDONESIA'],
            ['id' => 31, 'sandi_bank' => '050', 'nama_bank' => 'STANDARD CHARTERED BANK'],
            ['id' => 32, 'sandi_bank' => '052', 'nama_bank' => 'BANK ABN AMRO'],
            ['id' => 33, 'sandi_bank' => '053', 'nama_bank' => 'BANK KEPPEL TATLEE BUANA'],
            ['id' => 34, 'sandi_bank' => '054', 'nama_bank' => 'BANK CAPITAL INDONESIA, TBK.'],
            ['id' => 35, 'sandi_bank' => '057', 'nama_bank' => 'BANK BNP PARIBAS INDONESIA'],
            ['id' => 36, 'sandi_bank' => '058', 'nama_bank' => 'BANK UOB INDONESIA'],
            ['id' => 37, 'sandi_bank' => '059', 'nama_bank' => 'KOREA EXCHANGE BANK DANAMON'],
            ['id' => 38, 'sandi_bank' => '060', 'nama_bank' => 'RABOBANK INTERNASIONAL INDONESIA'],
            ['id' => 39, 'sandi_bank' => '061', 'nama_bank' => 'ANZ PANIN BANK'],
            ['id' => 40, 'sandi_bank' => '067', 'nama_bank' => 'DEUTSCHE BANK AG.'],
            ['id' => 41, 'sandi_bank' => '068', 'nama_bank' => 'BANK WOORI INDONESIA'],
            ['id' => 42, 'sandi_bank' => '069', 'nama_bank' => 'BANK OF CHINA LIMITED'],
            ['id' => 43, 'sandi_bank' => '076', 'nama_bank' => 'BANK BUMI ARTA'],
            ['id' => 44, 'sandi_bank' => '087', 'nama_bank' => 'BANK EKONOMI'],
            ['id' => 45, 'sandi_bank' => '088', 'nama_bank' => 'BANK ANTARDAERAH'],
            ['id' => 46, 'sandi_bank' => '089', 'nama_bank' => 'BANK HAGA'],
            ['id' => 47, 'sandi_bank' => '093', 'nama_bank' => 'BANK IFI'],
            ['id' => 48, 'sandi_bank' => '095', 'nama_bank' => 'BANK CENTURY, TBK.'],
            ['id' => 49, 'sandi_bank' => '097', 'nama_bank' => 'BANK MAYAPADA'],
            ['id' => 50, 'sandi_bank' => '110', 'nama_bank' => 'BANK JABAR'],
            ['id' => 51, 'sandi_bank' => '111', 'nama_bank' => 'BANK DKI'],
            ['id' => 52, 'sandi_bank' => '112', 'nama_bank' => 'BPD DIY'],
            ['id' => 53, 'sandi_bank' => '113', 'nama_bank' => 'BANK JATENG'],
            ['id' => 54, 'sandi_bank' => '114', 'nama_bank' => 'BANK JATIM'],
            ['id' => 55, 'sandi_bank' => '115', 'nama_bank' => 'BPD JAMBI'],
            ['id' => 56, 'sandi_bank' => '116', 'nama_bank' => 'BPD ACEH'],
            ['id' => 57, 'sandi_bank' => '117', 'nama_bank' => 'BANK SUMUT'],
            ['id' => 58, 'sandi_bank' => '118', 'nama_bank' => 'BANK NAGARI'],
            ['id' => 59, 'sandi_bank' => '119', 'nama_bank' => 'BANK RIAU'],
            ['id' => 60, 'sandi_bank' => '120', 'nama_bank' => 'BANK SUMSEL'],
            ['id' => 61, 'sandi_bank' => '121', 'nama_bank' => 'BANK LAMPUNG'],
            ['id' => 62, 'sandi_bank' => '122', 'nama_bank' => 'BPD KALSEL'],
            ['id' => 63, 'sandi_bank' => '123', 'nama_bank' => 'BPD KALIMANTAN BARAT'],
            ['id' => 64, 'sandi_bank' => '124', 'nama_bank' => 'BPD KALTIM'],
            ['id' => 65, 'sandi_bank' => '125', 'nama_bank' => 'BPD KALTENG'],
            ['id' => 66, 'sandi_bank' => '126', 'nama_bank' => 'BPD SULSEL'],
            ['id' => 67, 'sandi_bank' => '127', 'nama_bank' => 'BANK SULUT'],
            ['id' => 68, 'sandi_bank' => '128', 'nama_bank' => 'BPD NTB'],
            ['id' => 69, 'sandi_bank' => '129', 'nama_bank' => 'BPD BALI'],
            ['id' => 70, 'sandi_bank' => '130', 'nama_bank' => 'BANK NTT'],
            ['id' => 71, 'sandi_bank' => '131', 'nama_bank' => 'BANK MALUKU'],
            ['id' => 72, 'sandi_bank' => '132', 'nama_bank' => 'BPD PAPUA'],
            ['id' => 73, 'sandi_bank' => '133', 'nama_bank' => 'BANK BENGKULU'],
            ['id' => 74, 'sandi_bank' => '134', 'nama_bank' => 'BPD SULAWESI TENGAH'],
            ['id' => 75, 'sandi_bank' => '135', 'nama_bank' => 'BANK SULTRA'],
            ['id' => 76, 'sandi_bank' => '145', 'nama_bank' => 'BANK NUSANTARA PARAHYANGAN'],
            ['id' => 77, 'sandi_bank' => '147', 'nama_bank' => 'BANK SWADESI'],
            ['id' => 78, 'sandi_bank' => '151', 'nama_bank' => 'BANK MEGA'],
            ['id' => 79, 'sandi_bank' => '152', 'nama_bank' => 'BANK JASA JAKARTA'],
            ['id' => 80, 'sandi_bank' => '153', 'nama_bank' => 'BANK BUKOPIN'],
            ['id' => 81, 'sandi_bank' => '157', 'nama_bank' => 'BANK SYARIAH MANDIRI'],
            ['id' => 82, 'sandi_bank' => '159', 'nama_bank' => 'BANK BISNIS INTERNASIONAL'],
            ['id' => 83, 'sandi_bank' => '161', 'nama_bank' => 'BANK SRI PARTHA'],
            ['id' => 84, 'sandi_bank' => '162', 'nama_bank' => 'BANK JASA JAKARTA'],
            ['id' => 85, 'sandi_bank' => '164', 'nama_bank' => 'BANK HARDA INTERNASIONAL'],
            ['id' => 86, 'sandi_bank' => '166', 'nama_bank' => 'BANK MASPION INDONESIA'],
            ['id' => 87, 'sandi_bank' => '167', 'nama_bank' => 'BANK HAGAKITA'],
            ['id' => 88, 'sandi_bank' => '200', 'nama_bank' => 'BANK TABUNGAN NEGARA (PERSERO)'],
            ['id' => 89, 'sandi_bank' => '212', 'nama_bank' => 'BANK SYARIAH BUKOPIN'],
            ['id' => 90, 'sandi_bank' => '213', 'nama_bank' => 'BANK BNI SYARIAH'],
            ['id' => 91, 'sandi_bank' => '405', 'nama_bank' => 'BANK VICTORIA SYARIAH'],
            ['id' => 92, 'sandi_bank' => '425', 'nama_bank' => 'BANK JABAR BANTEN SYARIAH'],
            ['id' => 93, 'sandi_bank' => '426', 'nama_bank' => 'BANK MEGA SYARIAH'],
            ['id' => 94, 'sandi_bank' => '441', 'nama_bank' => 'BANK MUAMALAT'],
            ['id' => 95, 'sandi_bank' => '451', 'nama_bank' => 'BANK SYARIAH INDONESIA'],
            ['id' => 96, 'sandi_bank' => '503', 'nama_bank' => 'BANK WINDU KENTJANA'],
            ['id' => 97, 'sandi_bank' => '506', 'nama_bank' => 'BANK FINCONESIA'],
            ['id' => 98, 'sandi_bank' => '513', 'nama_bank' => 'BANK MAYORA'],
            ['id' => 99, 'sandi_bank' => '517', 'nama_bank' => 'BANK VICTORIA INTERNATIONAL'],
            ['id' => 100, 'sandi_bank' => '520', 'nama_bank' => 'BANK EKSEKUTIF INTERNASIONAL'],
            ['id' => 101, 'sandi_bank' => '521', 'nama_bank' => 'CENTRATAMA NASIONAL BANK'],
            ['id' => 102, 'sandi_bank' => '523', 'nama_bank' => 'BANK FAMA INTERNASIONAL'],
            ['id' => 103, 'sandi_bank' => '525', 'nama_bank' => 'BANK INA PERDANA'],
            ['id' => 104, 'sandi_bank' => '526', 'nama_bank' => 'BANK HARFA'],
            ['id' => 105, 'sandi_bank' => '531', 'nama_bank' => 'BANK KESEJAHTERAAN EKONOMI'],
            ['id' => 106, 'sandi_bank' => '535', 'nama_bank' => 'BANK ARTOS INDONESIA'],
            ['id' => 107, 'sandi_bank' => '536', 'nama_bank' => 'BANK PURBA DANARTA'],
            ['id' => 108, 'sandi_bank' => '542', 'nama_bank' => 'BANK MULTI ARTA SENTOSA'],
            ['id' => 109, 'sandi_bank' => '547', 'nama_bank' => 'BANK MAYBANK INDOCORP'],
            ['id' => 110, 'sandi_bank' => '548', 'nama_bank' => 'BANK OCBC – INDONESIA'],
            ['id' => 111, 'sandi_bank' => '553', 'nama_bank' => 'BANK OF CHINA LIMITED'],
            ['id' => 112, 'sandi_bank' => '555', 'nama_bank' => 'BANK BUMI ARTA'],
            ['id' => 113, 'sandi_bank' => '558', 'nama_bank' => 'BANK EKONOMI'],
            ['id' => 114, 'sandi_bank' => '559', 'nama_bank' => 'BANK ANTARDAERAH'],
            ['id' => 115, 'sandi_bank' => '562', 'nama_bank' => 'BANK HANA'],
            ['id' => 116, 'sandi_bank' => '564', 'nama_bank' => 'BANK MITSUI SUMITOMO INDONESIA'],
            ['id' => 117, 'sandi_bank' => '566', 'nama_bank' => 'BANK COMMONWEALTH'],
            ['id' => 118, 'sandi_bank' => '567', 'nama_bank' => 'BANK BJB SYARIAH'],
            ['id' => 119, 'sandi_bank' => '945', 'nama_bank' => 'BANK KEB HANA'],
            ['id' => 120, 'sandi_bank' => '946', 'nama_bank' => 'BANK CTBC INDONESIA'],
            ['id' => 121, 'sandi_bank' => '947', 'nama_bank' => 'BANK SBI INDONESIA'],
            ['id' => 122, 'sandi_bank' => '948', 'nama_bank' => 'BANK OF AMERICA NA'],
            ['id' => 123, 'sandi_bank' => '949', 'nama_bank' => 'BANK ING INDONESIA'],
            ['id' => 124, 'sandi_bank' => '950', 'nama_bank' => 'BANK UOB INDONESIA'],
            ['id' => 125, 'sandi_bank' => '951', 'nama_bank' => 'BANK ANZ INDONESIA'],
            ['id' => 126, 'sandi_bank' => '952', 'nama_bank' => 'DEUTSCHE BANK'],
            ['id' => 127, 'sandi_bank' => '954', 'nama_bank' => 'BANK CAPITAL INDONESIA'],
            ['id' => 128, 'sandi_bank' => '955', 'nama_bank' => 'BANK BNP PARIBAS INDONESIA'],
            ['id' => 129, 'sandi_bank' => '957', 'nama_bank' => 'BANK ARTHA GRAHA INTERNASIONAL'],
            ['id' => 130, 'sandi_bank' => '958', 'nama_bank' => 'BANK CREDIT AGRICOLE INDOSUEZ'],
            ['id' => 131, 'sandi_bank' => '959', 'nama_bank' => 'BANK TOKYO MITSUBISHI UFJ'],
            ['id' => 132, 'sandi_bank' => '961', 'nama_bank' => 'BANK DBS INDONESIA'],
            ['id' => 133, 'sandi_bank' => '963', 'nama_bank' => 'BANK RESONA PERDANIA'],
            ['id' => 134, 'sandi_bank' => '964', 'nama_bank' => 'BANK MIZUHO INDONESIA'],
            ['id' => 135, 'sandi_bank' => '965', 'nama_bank' => 'STANDARD CHARTERED BANK'],
            ['id' => 136, 'sandi_bank' => '967', 'nama_bank' => 'BANK ABN AMRO'],
            ['id' => 137, 'sandi_bank' => '968', 'nama_bank' => 'BANK KEDB HANA'],
            ['id' => 138, 'sandi_bank' => '969', 'nama_bank' => 'BANK BANGKOK'],
            ['id' => 139, 'sandi_bank' => '972', 'nama_bank' => 'BANK OF CHINA'],
            ['id' => 140, 'sandi_bank' => '987', 'nama_bank' => 'PRIMA MASTER BANK'],
            ['id' => 141, 'sandi_bank' => '988', 'nama_bank' => 'BANK AKITA'],
        ]);
    }
}
